/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDataResultFromDiscriminatorValue, type DataResult } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /data/{id}
 */
export interface DataItemRequestBuilder extends BaseRequestBuilder<DataItemRequestBuilder> {
    /**
     * Gets data
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DataResult>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DataResult | undefined>;
    /**
     * Gets data
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DataItemRequestBuilderUriTemplate = "{+baseurl}/data/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const DataItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DataItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createDataResultFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
